version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mafci_archive
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-key-for-development-only-please-change-in-production
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mafci_archive
      - REDIS_URL=redis://redis:6379/0
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  celery:
    build: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
      - backend
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-key-for-development-only-please-change-in-production
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mafci_archive
      - REDIS_URL=redis://redis:6379/0
    command: celery -A config worker --loglevel=info

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000/api
      - VITE_APP_NAME=MAFCI DigiArchive
    command: npm run dev -- --host 0.0.0.0

volumes:
  postgres_data:
