# Generated by Django 4.2.7 on 2025-07-23 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('document_upload', 'Document Upload'), ('document_process', 'Document Processing'), ('ocr_complete', 'OCR Complete'), ('share', 'Document Shared'), ('comment', 'New Comment'), ('tag', 'New Tag'), ('system', 'System Notification')], help_text='Type of notification', max_length=50)),
                ('title', models.CharField(help_text='Title of the notification', max_length=255)),
                ('message', models.TextField(help_text='Message content of the notification')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the notification was created')),
                ('document', models.ForeignKey(blank=True, help_text='Related document if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='documents.document')),
                ('user', models.ForeignKey(help_text='User who should receive the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
