# Generated by Django 4.2.7 on 2025-08-07 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0002_department_alter_documentocr_full_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('view', 'Viewed'), ('download', 'Downloaded'), ('share', 'Shared'), ('ocr', 'OCR Processed'), ('tag', 'Tagged'), ('untag', 'Untagged'), ('move', 'Moved')], help_text='Type of action performed', max_length=20)),
                ('object_id', models.PositiveIntegerField(help_text='ID of the object acted upon')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action was performed')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('description', models.TextField(blank=True, help_text='Description of the action performed')),
                ('changes', models.JSONField(blank=True, help_text='JSON field containing changes made', null=True)),
                ('content_type', models.ForeignKey(help_text='Type of object acted upon', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
